version: '3.8'

networks:
  default:
    name: private-network

services:
  usermanager:  
    build: .
    image: usermanager
    container_name: usermanager
    environment:
      SERVER_PORT: 9000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: user_db
      SSL_MODE: disable
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - postgres
    ports: 
      - "9000:9000"

  # Create service with RabbitMQ.
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672" # HTTP dashboard
      - "5672:5672" # Main rabbitmq port

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: 
      - "5432:5432"